### ISSUE TITLE
Video call hangup that hangs

### ISSUE THREAD

**Issue by root562** [matrix-org/matrix-android-sdk#496] opened 2019-09-23 12:21 UTC
Video call hangup in riot-android app caused program crash. Check out https://github.com/vector-im/riot-android/issues/3311 and https://github.com/vector-im/riot-android/issues/3266
Might be related to https://github.com/vector-im/riot-android/issues/501
Tracing the Riot 0.9.6 code for the bug. It happens at CallsManager.Java, onHangup(). mActiveCall.hangup() cause the program to crash. This is a call to SDK.

**Comment by awesome-manuel** [comment] 2019-12-10 09:44
This seems to be a regression introduced somewhere after v0.9.27.

**Comment by awesome-manuel** [comment] 2019-12-10 17:04
I was able to trace it down further. The call to `PeerConnectionFactory.dispose()` sometimes hangs in `nativeFreeFactory(this.nativeFactory);`. This might be a race condition between this action and something else going on in parallel.

Stange thing though is that `nativeFreeFactory(this.nativeFactory);` does nothing that could actually block.

Futhermore `WebRTCModule` from `react-native-webrtc` never calls `PeerConnectionFactory.dispose()` at all. Maybe matrix-android-sdk needs something similar to keep track of the global PeerConnectionFactory.

**Comment by root562** [comment] 2019-12-11 05:16
I presume the PeerConnectionFactory.dispose() is inside matrix-android-sdk. I have only looked at the code of riot-android but not the SDK. Hopefully there is a fix coming soon.

**Comment by awesome-manuel** [comment] 2019-12-11 08:26
It works for me, when I increase the minSdkVersion to 21. Nevertheless there are also updates for `react-native-webrtc` and `jitsi-meet` that could be integrated as well.

**Comment by root562** [comment] 2019-12-12 03:28
> It works for me, when I increase the minSdkVersion to 21. Nevertheless there are also updates for `react-native-webrtc` and `jitsi-meet` that could be integrated as well.

I tried your suggestion. The problem is now intermittent. Sometime the program hangs, sometimes it behaves properly. Will do further testing.

**Comment by root562** [comment] 2019-12-13 01:54
The probability of program hang happens more for the one doing the hangup( the one who clicks on the hangup button).

**Comment by awesome-manuel** [comment] 2019-12-13 10:50
You're right, it still hangs sometimes. I did a complete refactoring of MXWebRtcCall.java during debugging, extracting a MXWebRtcClient.java similar to [PeerConnectionClient.java](https://chromium.googlesource.com/external/webrtc/+/refs/heads/master/examples/androidapp/src/org/appspot/apprtc/PeerConnectionClient.java). See https://github.com/Awesome-Technologies/matrix-android-sdk/commit/98cb1872da5f0815d9fe0930674c3ae77aac3927
But the only thing that helped was to remove the call to `mPeerConnectionFactory.dispose()`.

**Comment by root562** [comment] 2019-12-14 03:43
Does removing  the call to mPeerConnectionFactory.dispose() has any side effects?

**Comment by awesome-manuel** [comment] 2019-12-14 07:26
For the short term: no
But I haven't monitored the memory consumption over the long term.

**Comment by root562** [comment] 2019-12-31 08:51
I just took some time learning to compile the riot-android with the SDK linked locally. Tried your suggestion by removing the call to mPeerConnectionFactory.dispose(). So far no more program hang. Looks like the call mPeerConnectionFactory.dispose() is a call to WebRTC sdk. My guess is there are 2 possibilities.
1. Something wrong with the way dispose() function is being used inside matrix-android-sdk. Perhaps something needs to be done or some resource needs to be released before that.
2. The bug is inside WebRTC sdk. 
PS: I am new to Android programming(coming from embedded domain), so I could be wrong.

**Comment by awesome-manuel** [comment] 2020-01-14 12:40
This beta app has minSdkVersion 21 and removes the call to `mPeerConnectionFactory.dispose()`: https://play.google.com/apps/testing/chat.amp.messenger

**Comment by rajil** [comment] 2020-01-15 18:31
@awesome-manuel I am trying to install it on Samsung Note 9 (SM-N960F) but google play says "This app is incompatible with all of your devices." 
Is there any restrictions on installing the app?

**Comment by rajil** [comment] 2020-01-16 17:29
This bug is a dealbreaker in using Riot. Is anybody in matrix/riot investigating this?
Which version should I install which doesn't have this bug?

**Comment by rajil** [comment] 2020-01-30 05:05
Is anybody investigating this bug?

**Comment by bmarty** [comment] 2020-02-06 15:46
I am :)

**Comment by rajil** [comment] 2020-02-07 03:19
@bmarty, thanks for the fix. When do we expect this to land on google playstore?

**Comment by bmarty** [comment] 2020-02-07 08:50
I will prepare a release today and push it to prod on Monday if everything is ok

**Comment by bmarty** [comment] 2020-02-07 10:29
Fixed by matrix-org/matrix-android-sdk#525

**Closed by bmarty** 2020-02-07 10:29 UTC

**Comment by rajil** [comment] 2020-02-10 07:16
@bmarty Any show stoppers for the release?

**Comment by bmarty** [comment] 2020-02-13 06:42
The release v0.9.10 is now live

**Comment by rajil** [comment] 2020-02-13 08:30
Thanks for the quick turnaround @bmarty. I have tested it and it working great for Android to Android calls. However, Android to IOS (riot-IOS) are failing right away. The call gets rejected and the Video UI does not come up. Don't known whether the issue is Android side or IOS side.
